### ISSUE TITLE
mysql absent failed

### ISSUE THREAD

**Issue by lxyu** [example42/puppet-mysql#13]
ENV: Ubuntu 12.10 + puppet 2.7.18-1ubuntu1

Apply this .pp file, and mysql installed successfully.
```puppet
class { "mysql": }
```

Then apply this .pp file. After it applied, mysql is still running.
```puppet
class { "mysql":
  absent => true,
}
```

Then try enable mysql again, apply this file:
```puppet
class { "mysql": }
```

It will be failed with this err:

>err: /Stage[main]/Mysql/Service[mysql]: Failed to call refresh: Could not start Service[mysql]: Execution of '/sbin/start mysql' returned 1:  at xxx/modules/example42/mysql/manifests/init.pp:352

**Comment by israelriibeiro** [comment]
@lermit , test it.  It worked. But i did tiny change: i use subscribe instead of notify .Without this change, this happens:

Notice: /Stage[main]/Mysql/Exec[post-remove]/returns: mysqld: no process found
Error: /Stage[main]/Mysql/Exec[post-remove]: Failed to call refresh: /usr/bin/killall -9 mysqld_safe mysqld returned 1 instead of one of [0]
Error: /Stage[main]/Mysql/Exec[post-remove]: /usr/bin/killall -9 mysqld_safe mysqld returned 1 instead of one of [0]

I tested this on debian 7.5.  I don't know why this happened: notify should mean something like before. If you need me to do more test, please, let me know it.
